/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import symbols.*;
import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
    @Test public void testRational() {
        Rational r1 = new Rational(1,2);
        Rational r2 = new Rational(2,4);
        assertEquals("2/4 should become 1/2",r1.toString(),r2.toString());
        try {
            new Rational(1,0);
            fail("Uh oh, 1/0 was valid!");
        } catch (Exception e) {
            System.out.println("No divide by zeros here");
        }
    }
    @Test public void testExpressions(){
        String exp = "2 + 3 * 4 - 5 ^ 2";
        int result = -11;
    }
}